### ISSUE TITLE
update Wordpress to 4.73

### ISSUE THREAD

**Issue by nueracloud** [uboslinux/ubos-wordpress#13]
Can the Wordpress app be updated easily or can you please update it at ubos level ?

**Comment by jernst** [comment]
Next beta. In develop, as you can see, we are at 4.7.3: https://github.com/uboslinux/ubos-wordpress/blob/develop/wordpress/PKGBUILD

**Comment by nueracloud** [comment]
The current 4.6 is sorta unusable and won't allow auto update, etc.  It all works ok just too out-of-date and won't allow upgrading through normal methods.

**Comment by nueracloud** [comment]
Next beta is due ?

**Comment by jernst** [comment]
It is not supposed to auto-update. UBOS does the upgrades when they are ready. Soapbox: "uncoordinated updates are the No 1 cause of broken personal servers"

**Comment by nueracloud** [comment]
Ok, please let me know when the next beta and WP update. thank you.

**Comment by nueracloud** [comment]
thanks
